/*
* Copyright (c) 2024 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
import LazyDataSource from '../util/LazyDataSource';

export class Data {
  private static instance: Data;
  lazyDataSource: LazyDataSource<DataSource> = new LazyDataSource();
  static readonly IMAGES: Resource[] = [$r(('app.media.realImageGen_shop_5')), $r(('app.media.realImageGen_shop_2')),
    $r(('app.media.realImageGen_shop_3')),
    $r(('app.media.realImageGen_shop_4'))];
  static readonly TITLE_LABELS: string[] = ['新品', '热卖', '', '限时'];
  static readonly TITLES: string[] = ['智能音箱', '无线耳机', '运动手环', '蓝牙键盘'];
  static readonly PRICE_TENS: string[] = ['299', '599', '199', '159'];
  static readonly PRICE_DOTS: string[] = ['.00', '.50', '.90', '.80'];
  static readonly PRICE_LABELS: string[] = ['补贴', '补贴', '', '补贴'];
  static readonly DES_LABELS: string[][] =
    [['AI语音', '家居控制'], ['降噪', '长续航'], ['心率监测', '防水'], ['机械轴', '多设备']];

  constructor() {
  }

  public static getInstance(): Data {
    if (!Data.instance) {
      Data.instance =
        new Data();
    }
    return Data.instance;
  }

  /**
   * Data loaded on current view converts network data into rendering data
   */
  getResources(): Promise<void> {
    /**
     * use your web request here
     */
    return new Promise((resolve: Function) => {
      const modelList: Array<DataSource> = [];
      for (let index = 0; index < Data.IMAGES.length;
        index++) {
        modelList.push(new DataSource(
          Data.IMAGES[index],
          Data.TITLE_LABELS[index],
          Data.TITLES[index],
          Data.PRICE_TENS[index],
          Data.PRICE_DOTS[index],
          Data.PRICE_LABELS[index],
          Data.DES_LABELS[index]
        ));
      }
      this.lazyDataSource.pushArrayData(modelList);
      resolve();
    });
  }
}

export class DataSource {
  private image: Resource;
  private title_label: string;
  private title: string;
  private price_ten: string;
  private price_dot: string;
  private price_label: string;
  private des_labels: string[];

  constructor(image: Resource, title_label: string, title: string,
    price_ten: string, price_dot: string, price_label: string, des_labels: string[]) {
    this.image = image;
    this.title_label = title_label;
    this.title = title;
    this.price_ten = price_ten;
    this.price_dot = price_dot;
    this.price_label = price_label;
    this.des_labels = des_labels;
  }

  getImage(): Resource {
    return this.image
  }

  getTitleLabel(): string {
    return this.title_label;
  }

  getTitle(): string {
    return this.title;
  }

  getPriceTen(): string {
    return this.price_ten;
  }

  getPriceDot(): string {
    return this.price_dot;
  }

  getPriceLabel(): string {
    return this.price_label;
  }

  getDesLabels(): string[] {
    return this.des_labels;
  }
}